application: baltimorevacants
version: 2
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

builtins:
- datastore_admin: on

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /static
  static_dir: static

- url: /data/.*
  script: data.py

- url: /m
  static_files: mobile.html
  upload: mobile.html

- url: /
  static_files: index.html
  upload: index.html